#if !COMBAT_SERVER

using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;
#endif
using CombatCore.SerializationTimeLine;
using Fort23.UTool;
using UTool.CustomizeTimeLogic.FxLogic.TimeLineEventLogic;

[System.Serializable]
public class TimeLineTriggerSerialization : TimeLineAssetSerialization
{
 
    public TimeLineTriggerType tineLineTrigerType;
    [Header("触发额外数据")] public string tineLineTrigerData;
    public TimeLineTriggerSerialization()
    {
        
    }
#if !COMBAT_SERVER

    public TimeLineTriggerSerialization(PlayableDirector playableDirector, GroupTrack groupTrack,
        TimelineClip timelineClip) : base(groupTrack, timelineClip)
    {
        TimeLineTriggerAsset timeLineTriggerAsset = timelineClip.asset as TimeLineTriggerAsset;
        targetEntityType = timeLineTriggerAsset.targetEntityType;
        tineLineTrigerType = timeLineTriggerAsset.tineLineTrigerType;
        tineLineTrigerData = timeLineTriggerAsset.tineLineTrigerData;
    }
#endif
    public override TimeLineEventLogicBasic CreateLogic()
    {
        return new TimeLineTimeTriggerEventLogicBasic();
    }
}